spring: 
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
       - id: PaymentMS
         uri: lb://PaymentMS
         predicates:
          - Path=/Ekart/payment-api/**
       - id: ProductMS
         uri: lb://ProductMS
         predicates: 
          - Path=/Ekart/product-api/**
       - id: CartMS
         uri: lb://CartMS
         predicates: 
          - Path=/Ekart/customercart-api/**
       - id: CustomerMS
         uri: lb://CustomerMS
         predicates:
          - Path=/Ekart/** 
       
       
            
         
      
